

# Configure a default setup of Home Assistant (frontend, api, etc)
# default_config:

config:
frontend:
  themes: 
    default:
      header-height: 44px
mobile_app:
person:
ssdp:
sun:
system_health:
updater:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
   base_url: muizeluuk.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include_dir_merge_named customize/
  unit_system: metric
  time_zone: Europe/Amsterdam

alarm_control_panel:
  - platform: manual
    name: Huis

browser_mod:

logger:
  default: critical

matrix:
  homeserver: https://matrix.org
  username: "@takkie-ha:matrix.org"
  password: !secret matrix
  rooms:
    - !secret matrix-room

media_player:
  - platform: androidtv
    host: 192.168.200.149
    name: "TV"
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037
    get_sources: false
    apps:
      com.google.android.tvlauncher: "Home"
      com.amazon.amazonvideo.livingroom: "Amazon"
      com.netflix.ninja: "Netflix"
      nl.nlziet: "NLZiet"
      com.plexapp.android: "Plex"
      com.appgeneration.itunerfree: "Radio"
      com.spotify.tv.android: "Spotify"
      com.aspiro.tidal: "Tidal"
      com.google.android.youtube.tv: "Youtube"
      com.nvidia.tegrazone3: "Geforce NOW"
      org.dolphinemu.dolphinemu: "Dolphin"
      com.retroarch: "RetroArch"

notify:
  - platform: group
    name: all
    services:
      - service: mobile_app_hdb_iphone_1902 # Ramon
      - service: mobile_app_hdb_iphone_van_f_s_o_7101 # Flore
  - platform: group
    name: flore
    services:
      - service: mobile_app_hdb_iphone_van_f_s_o_7101 # Flore
  - platform: group
    name: ramon
    services:
      - service: mobile_app_hdb_iphone_1902 # Ramon
  - name: matrix
    platform: matrix
    default_room: !secret matrix-room

recorder:
  purge_keep_days: 30
  include:
    domains:
      - alarm_control_panel
      - person
      - input_boolean
      - input_select
      - sensor
      - binary_sensor
      - vacuum

######################################################################

#alert: !include_dir_merge_named alerts/
automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensors/
counter: !include_dir_merge_named counters/
group: !include_dir_merge_named groups/
history: !include history.yaml
input_boolean: !include_dir_merge_named input_boolean/
input_number: !include_dir_merge_named input_number/
input_select: !include_dir_merge_named input_select/
logbook: !include logbook.yaml
#notify: !include_dir_list notify/
python_script:
scene: !include_dir_merge_list scenes/
sensor: !include_dir_merge_list sensors/
script: !include_dir_merge_named scripts/
timer: !include_dir_merge_named timers/
zone: !include_dir_list zones/


