

# Configure a default setup of Home Assistant (frontend, api, etc)
# default_config:

# automation:
config:
frontend:
mobile_app:
person:
ssdp:
sun:
system_health:
updater:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
   base_url: muizeluuk.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include customize.yaml
  unit_system: metric

alarm_control_panel:
  - platform: manual

emulated_hue:
  listen_port: 80

logger:
  default: warning

media_player:
  - platform: androidtv
    host: 192.168.200.149
    name: "NVidia Shield"
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037
    get_sources: false
    apps:
      com.google.android.tvlauncher: "Home"
      com.amazon.amazonvideo.livingroom: "Amazon"
      com.netflix.ninja: "Netflix"
      nl.nlziet: "NLZiet"
      com.plexapp.android: "Plex"
      com.appgeneration.itunerfree: "Radio"
      com.spotify.tv.android: "Spotify"
      com.aspiro.tidal: "Tidal"
      com.google.android.youtube.tv: "Youtube"

notify:
  - platform: group
    name: all
    services:
      - service: mobile_app_iphone
      - service: mobile_app_hasskit_iphone_8999
      - service: mobile_app_iphone_van_f_s_o


################################################################################
################################################################################

#media_player:
  # Use the Python ADB implementation without authentication
#  - platform: androidtv
#    name: Living Room ATV
#    host: 192.168.200.149

# Homekit integration
homekit:
  auto_start: false
  safe_mode: false
  filter:
    exclude_domains:
      - automation
      - device_tracker
      - alarm_control_panel
      - sensor
      - binary_sensor
    exclude_entities:
      - binary_sensor.updater
    include_entities:
      - sensor.temperature_4
#      include_domains:
#        - alarm_control_panel
#        - light
#      exclude_entities:
#        - light.

######################################################################
# Includes

#alert: !include_dir_merge_named alerts/
automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_list binary_sensors/
group: !include_dir_merge_named groups/
#history: !include history.yaml
input_boolean: !include_dir_merge_named input_boolean/
input_number: !include_dir_merge_named input_number/
#input_select: !include_dir_merge_named input_select/
#logbook: !include logbook.yaml
#notify: !include_dir_list notify/
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_named scripts/
timer: !include_dir_merge_named timers/
sensor: !include_dir_list sensors/
zone: !include_dir_list zones/


