

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

config:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.3
    - 172.30.33.2
    - 127.0.0.1
    - ::1

frontend:
  themes: 
    default:
      header-height: 44px
mobile_app:
person:
#ssdp: used for discovery
sun:
system_health:
updater:
websocket_api:



# Text to speech
tts:
  - platform: google_translate
    language: 'nl'
    service_name: google_say
    cache: true

homeassistant:
  customize: !include_dir_merge_named customize/
  unit_system: metric
  time_zone: Europe/Amsterdam

alarm_control_panel:
  - platform: manual
    name: Huis

#browser_mod:

#emulated_hue:
#  listen_port: 80

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: takkie
  password: !secret influxdb
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - alarm_control_panel
      - sun
    entity_globs:
      - binary_sensor.beweging_*
      - binary_sensor.aanwezigheid_*
      - binary_sensor.*_aanwezigheid_detectie
      - binary_sensor.*_lichtstatus
      - binary_sensor.slaapkamer_*
      - binary_sensor.woonkamer_*
      - binary_sensor.hal_*
      - binary_sensor.buiten_*
      - binary_sensor.lekkage_wasmachine
      - sensor.beweging_*
      - sensor.licht_*
      - sensor.luchtdruk_*
      - sensor.luchtvochtigheid_*
      - sensor.temperatuur_*
      - sensor.delft*
      - sensor.*batterij
      - person.*


logger:
  default: info
  logs:
    # pydeconz: debug
    # homeassistant.components.deconz: debug
    custom_components.localtuya: debug
    
notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_chatid
  - platform: group
    name: all
    services:
      - service: mobile_app_iphone_ramon # Ramon
      - service: mobile_app_iphone_van_f_s_o # Flore
  - platform: group
    name: flore
    services:
      - service: mobile_app_iphone_van_f_s_o # Flore
  - platform: group
    name: ramon
    services:
      - service: mobile_app_iphone_ramon # Ramon

recorder:
  purge_keep_days: 365
  include:
    domains:
      - person
      - input_boolean
      - binary_sensor
    entities:
      - sensor.cpu_temperatuur
      - sensor.disk_use_percent
      - sensor.memory_use_percent
      - sensor.shellyplug_energy
      - sensor.shellyplug_power
      - sensor.licht_woonkamer
      - sensor.temperatuur_buiten
      - sensor.temperatuur_slaapkamer
      - sensor.temperatuur_woonkamer
      - sensor.luchtdruk_buiten
      - sensor.luchtdruk_woonkamer
      - sensor.luchtvochtigheid_buiten
      - sensor.luchtvochtigheid_slaapkamer
      - sensor.luchtvochtigheid_woonkamer
      - binary_sensor.drinkbak
      - switch.drinkbak
      - person.flore
      - person.ramon

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatid

######################################################################

#alert: !include_dir_merge_named alerts/
automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensors/
counter: !include_dir_merge_named counters/
group: !include_dir_merge_named groups/
history: !include history.yaml
input_boolean: !include_dir_merge_named input_boolean/
input_number: !include_dir_merge_named input_number/
input_select: !include_dir_merge_named input_select/
logbook: !include logbook.yaml
#notify: !include_dir_list notify/
python_script:
scene: !include_dir_merge_list scenes/
sensor: !include_dir_merge_list sensors/
script: !include_dir_merge_named scripts/
timer: !include_dir_merge_named timers/
utility_meter: !include_dir_merge_named utility_meter/
zone: !include_dir_list zones/


