

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

config:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.3
    - 172.30.33.2
    - 127.0.0.1
    - ::1
energy:
ffmpeg:
frontend:
  # themes: 
    # default:
      # header-height: 44px
history: 
media_source:
mobile_app:
person:
#ssdp: used for discovery
stream:
sun:
system_health:
#updater:
websocket_api:


homeassistant:
  packages: !include_dir_merge_named packages/
  unit_system: metric
  time_zone: Europe/Amsterdam
  country: NL

logger:
  default: info
  # logs:
    # pydeconz: debug
    # homeassistant.components.deconz: debug
    # custom_components.dahua: debug
    # homeassistant.components.shell_command: debug

recorder:
  purge_keep_days: 30
  include:
    domains:
      # Beveiliging
      - alarm_control_panel
      # Klimaat
      - climate
    entities:
      # Energie
      - sensor.irradiance
      - sensor.shellyplug_energy
      - sensor.shellyplug_power
      - sensor.zonnepanelen_power
      - sensor.zonnepanelen_energy
      - sensor.zonnepanelen_radiation
      # Weer (KNMI fallback voor buitentemperatuur)
      - sensor.knmi_temperature
    entity_globs:
      # Energie
      - sensor.p1_*
      # Klimaat
      - sensor.temperatuur_*
      - sensor.luchtvochtigheid_*
      - sensor.luchtdruk_*
      - sensor.luchtkwaliteit_*
      - sensor.licht_*
      # Weer
      - sensor.weerstation*
automation: !include_dir_merge_list automations/
input_boolean: !include_dir_merge_named input_boolean/
logbook: !include logbook.yaml


