

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

config:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.3
    - 172.30.33.2
    - 127.0.0.1
    - ::1
energy:
ffmpeg:
frontend:
  # themes: 
    # default:
      # header-height: 44px
history: 
media_source:
mobile_app:
person:
#ssdp: used for discovery
stream:
sun:
system_health:
#updater:
websocket_api:


homeassistant:
  customize: !include_dir_merge_named customize/
  unit_system: metric
  time_zone: Europe/Amsterdam
  country: NL

alarm_control_panel:
  - platform: manual
    name: Huis

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: takkie
  password: !secret influxdb
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - alarm_control_panel
      - sun
      - vacuum
      - sensor.zonnepanelen_power
      - sensor.zonnepanelen_energy
    entity_globs:
      - binary_sensor.beweging_*
      - binary_sensor.aanwezigheid_*
      - binary_sensor.*_aanwezigheid_detectie
      - binary_sensor.*_lichtstatus
      - binary_sensor.slaapkamer_*
      - binary_sensor.woonkamer_*
      - binary_sensor.hal_*
      - binary_sensor.buiten_*
      - binary_sensor.lekkage_wasmachine
      - sensor.beweging_*
      - sensor.licht_*
      - sensor.luchtdruk_*
      - sensor.luchtvochtigheid_*
      - sensor.temperatuur_*
      - sensor.delft*
      - sensor.knmi_thuis_*
      - sensor.*batterij
      - sensor.p1_*
      - sensor.omvormer_*
      - person.*
      - sensor.ventilator_woonkamer_*
      - sensor.heatbooster*

logger:
  default: info
  # logs:
    # pydeconz: debug
    # homeassistant.components.deconz: debug
    # custom_components.dahua: debug
    # homeassistant.components.shell_command: debug

recorder:
  purge_keep_days: 3650
  include:
    domains:
      - person
      - vacuum
    entities:
      - sensor.cpu_temperatuur
      - sensor.disk_use_percent
      - sensor.memory_use_percent
      - sensor.shellyplug_energy
      - sensor.shellyplug_power
      - binary_sensor.drinkbak
      - switch.drinkbak
      - sensor.co2
      - sensor.irradiance
      - sensor.zonnepanelen_power
      - sensor.zonnepanelen_energy
      - sensor.knmi_thuis_waarschuwing
      - sensor.knmi_thuis_wind
      - sensor.buienradar_precipitation
      - sensor.buienradar_wind_force
      - sensor.buienradar_wind_gust
    entity_globs:
      - sensor.p1_*
      - sensor.omvormer_*
      - sensor.luchtvochtigheid_*
      - sensor.temperatuur_*
      - sensor.luchtdruk_*
      - sensor.licht_*
      - sensor.ventilator_woonkamer_*
      - sensor.heatbooster*
######################################################################

#alert: !include_dir_merge_named alerts/
automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensors/

fan: !include_dir_merge_list fan/
group: !include_dir_merge_named groups/
input_boolean: !include_dir_merge_named input_boolean/
input_number: !include_dir_merge_named input_number/
input_select: !include_dir_merge_named input_select/
logbook: !include logbook.yaml
python_script:
rest_command: !include rest_command.yaml
scene: !include_dir_merge_list scenes/
sensor: !include_dir_merge_list sensors/
template: !include_dir_merge_list templates/
script: !include_dir_merge_named scripts/
timer: !include_dir_merge_named timers/
utility_meter: !include_dir_merge_named utility_meter/
zone: !include_dir_list zones/


