

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

config:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.3
    - 172.30.33.2
    - 127.0.0.1
    - ::1
frontend:
  themes: 
    default:
      header-height: 44px
mobile_app:
person:
#ssdp: used for discovery
sun:
system_health:
updater:
websocket_api:



# Text to speech
tts:
  - platform: google_translate
    language: 'nl'
    service_name: google_say
    cache: true

homeassistant:
  customize: !include_dir_merge_named customize/
  unit_system: metric
  time_zone: Europe/Amsterdam

alarm_control_panel:
  - platform: manual
    name: Huis

#browser_mod:

#emulated_hue:
#  listen_port: 80

logger:
  default: info
  logs:
    # pydeconz: debug
    # homeassistant.components.deconz: debug
    custom_components.localtuya: debug
    
notify:
  - platform: group
    name: all
    services:
      - service: mobile_app_iphone_ramon # Ramon
      - service: mobile_app_iphone_van_f_s_o # Flore
  - platform: group
    name: flore
    services:
      - service: mobile_app_iphone_van_f_s_o # Flore
  - platform: group
    name: ramon
    services:
      - service: mobile_app_iphone_ramon # Ramon

recorder:
  purge_keep_days: 31
  include:
    domains:
      - person
      - input_boolean
      - binary_sensor
    entities:
      - sensor.cpu_temperatuur
      - sensor.disk_use_percent
      - sensor.memory_use_percent
      - sensor.licht_woonkamer
      - sensor.temperatuur_buiten
      - sensor.temperatuur_slaapkamer
      - sensor.temperatuur_woonkamer
      - sensor.luchtdruk_buiten
      - sensor.luchtdruk_woonkamer
      - sensor.luchtvochtigheid_buiten
      - sensor.luchtvochtigheid_slaapkamer
      - sensor.luchtvochtigheid_woonkamer
      - binary_sensor.drinkbak
      - switch.drinkbak
      - person.flore
      - person.ramon
######################################################################

#alert: !include_dir_merge_named alerts/
automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensors/
counter: !include_dir_merge_named counters/
group: !include_dir_merge_named groups/
history: !include history.yaml
input_boolean: !include_dir_merge_named input_boolean/
input_number: !include_dir_merge_named input_number/
input_select: !include_dir_merge_named input_select/
logbook: !include logbook.yaml
#notify: !include_dir_list notify/
python_script:
scene: !include_dir_merge_list scenes/
sensor: !include_dir_merge_list sensors/
script: !include_dir_merge_named scripts/
timer: !include_dir_merge_named timers/
utility_meter: !include_dir_merge_named utility_meter/
zone: !include_dir_list zones/


