- alias: Ventilatie – preset stuurt ventilatiestand
  trigger:
    - platform: state
      entity_id: input_select.ventilatie_preset
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_select.ventilatie_preset
              state: 'cooling'
          sequence:
            - service: script.set_ventilatie_stand
              data:
                percentage: 100
        - conditions:
            - condition: state
              entity_id: input_select.ventilatie_preset
              state: 'boost'
          sequence:
            - service: script.set_ventilatie_stand
              data:
                percentage: 66
        - conditions:
            - condition: state
              entity_id: input_select.ventilatie_preset
              state: 'normal'
          sequence:
            - service: script.set_ventilatie_stand
              data:
                percentage: 33
        - conditions:
            - condition: state
              entity_id: input_select.ventilatie_preset
              state: 'off'
          sequence:
            - service: script.set_ventilatie_stand
              data:
                percentage: 0
        - conditions:
            - condition: state
              entity_id: input_select.ventilatie_preset
              state: 'manual'
          sequence: []