- alias: Update multiple simulated device trackers
  trigger:
  - platform: state
    entity_id:
      - input_boolean.tracker_homekit_flore
      - input_boolean.tracker_homekit_ramon
  variables:
    person_name: "{{ trigger.entity_id.split('_')[-1] | capitalize }}"
  action:
    - service: device_tracker.see
    data:
      dev_id: "tracker_{{ person_name | lower }}"
      host_name: "Tracker {{ person_name }}"
      location_name: >
      {% if trigger.to_state.state == 'on' %}
          home
      {% else %}
          not_home
      {% endif %}