# Uiteindelijke sensor
- platform: min_max
  name: 'Aanwezigheid Flore'
  type: max
  entity_ids:
    - sensor.aanwezigheid_flore_bg
    - sensor.aanwezigheid_flore_1g
- platform: min_max
  name: 'Aanwezigheid Ramon'
  type: max
  entity_ids:
    - sensor.aanwezigheid_ramon_bg
    - sensor.aanwezigheid_ramon_1g
- platform: min_max
  name: 'Aanwezigheid Sissel'
  type: max
  entity_ids:
    - sensor.aanwezigheid_sissel_bg
    - sensor.aanwezigheid_sissel_1g

###### Sensoren per verdieping

#Slaapkamer (RPi Zero)
- platform: mqtt
  name: 'Aanwezigheid Flore 1G'
  state_topic: 'location/monitor/bedroom/iphone_flore'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: 'Aanwezigheid Ramon 1G'
  state_topic: 'location/monitor/bedroom/iphone_ramon'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: 'Aanwezigheid Sissel 1G'
  state_topic: 'location/monitor/bedroom/iphone_sissel'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'

# Begane grond (Raspberry Pi 3B+)
- platform: mqtt
  name: 'Aanwezigheid Flore BG'
  state_topic: 'aanwezigheid/beganegrond/flore'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: 'Aanwezigheid Ramon BG'
  state_topic: 'aanwezigheid/beganegrond/ramon'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: 'Aanwezigheid Sissel BG'
  state_topic: 'aanwezigheid/beganegrond/sissel'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'