- platform: statistics
  name: Luchtvochtigheid badkamer (statistics)
  entity_id: sensor.luchtvochtigheid_badkamer
  sampling_size: 100
  max_age:
    hours: 48

- platform: statistics
  name: Luchtvochtigheid slaapkamer (statistics)
  entity_id: sensor.luchtvochtigheid_slaapkamer
  sampling_size: 100
  max_age:
    hours: 48

- platform: statistics
  name: CO2 statistics 15m
  entity_id: sensor.co2
  sampling_size: 15
  max_age:
    hours: 8

- platform: statistics
  name: CO2 statistics 5m
  entity_id: sensor.co2
  sampling_size: 5
  max_age:
    hours: 8