# Sensor die de laatste oppervlakte van het stofzuigen weergeeft (2021-11 valetudo)
- platform: rest
  name: Stofzuiger totale oppervlakte
  #resource: http://192.168.200.127/api/v2/robot/state/attributes
  resource: http://192.168.200.127/api/v2/robot/capabilities/TotalStatisticsCapability
  value_template: "{{ value_json[1].value | float(0) / 10000 | int(0) }}"