# Sensor based binary_sensors
- platform: template
  sensors:
    aanwezigheid_hal:
      friendly_name: "Hal"
      device_class: occupancy
      value_template: >-
          {{
              is_state('binary_sensor.hal', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_badkamer:
      friendly_name: "Badkamer"
      device_class: occupancy
      value_template: >-
          {{ 
              is_state('binary_sensor.badkamer', 'on') or
              is_state('binary_sensor.badkamer_radar', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_slaapkamer:
      friendly_name: "Slaapkamer"
      device_class: occupancy
      value_template: >-
          {{
              is_state('binary_sensor.slaapkamer', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_woonkamer:
      friendly_name: "Woonkamer"
      device_class: occupancy
      value_template: >-
          {{
              is_state('binary_sensor.woonkamer_beweging', 'on')
          }}