######## Aanwezigheidssensoren voor kamers
- platform: template
  sensors:
    aanwezigheid_hal:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_hal') }) }}
      value_template: >-
          {{
              is_state('group.beweging_hal', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_badkamer:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_badkamer') }) }}
      value_template: >-
          {{ 
              is_state('group.beweging_badkamer', 'on')
          }}
