######## Aanwezigheidssensoren voor kamers
#### ESP regelt sensoren, hier kunnen evt zones worden gecombineerd, of xiaomi sensoren worden toegevoegd
- platform: template
  sensors:
    aanwezigheid_hal:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      value_template: >-
          {{
              is_state('timer.hal', 'active') or
              is_state('binary_sensor.beweging_hal', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_badkamer:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      value_template: >-
          {{ 
            is_state('timer.badkamer', 'active') or
              is_state('binary_sensor.beweging_badkamer', 'on')
          }}
