######## Aanwezigheidssensoren voor kamers
#### ESP regelt sensoren, hier kunnen evt zones worden gecombineerd, of xiaomi sensoren worden toegevoegd
- platform: template
  sensors:
    aanwezigheid_hal:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      value_template: >-
          {{
              is_state('binary_sensor.hal', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_badkamer:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      value_template: >-
          {{ 
              is_state('binary_sensor.badkamer', 'on') or
              is_state('binary_sensor.badkamer_radar', 'on')
          }}
