# Sensor based binary_sensors
- platform: template
  sensors:
    aanwezigheid_hal:
      friendly_name: "Hal"
      device_class: occupancy
      delay_off:
        minutes: "{{ states('input_number.kamers_aanwezigheid_hal') }}"
      value_template: >-
          {{
              is_state('binary_sensor.hal', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_badkamer:
      friendly_name: "Badkamer"
      device_class: occupancy
      delay_off:
        minutes: 3
      value_template: >-
          {{ 
              is_state('binary_sensor.badkamer', 'on') or
              is_state('binary_sensor.badkamer_radar', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_slaapkamer:
      friendly_name: "Slaapkamer"
      device_class: occupancy
      delay_off:
        minutes: 1
      value_template: >-
          {{
              is_state('binary_sensor.slaapkamer', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_woonkamer:
      friendly_name: "Woonkamer"
      device_class: occupancy
      delay_off:
        minutes: 5
      value_template: >-
          {{
              is_state('binary_sensor.woonkamer_beweging', 'on')
          }}
# Binary_sensors to override sensors above. In special circumstances
- platform: template
  sensors:
    aanwezigheid_hal_override:
      friendly_name: "Hal override"
      delay_off:
        minutes: 0
      value_template: >-
          {{ 
            is_state('input_boolean.scene_special_wolf_in_bed', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_badkamer_override:
      friendly_name: "Badkamer override"
      value_template: >-
          {{ 
            is_state('input_boolean.scene_special_wolf_in_bed', 'on')
          }}
- platform: template
  sensors:
    aanwezigheid_slaapkamer_override:
      friendly_name: "Slaapkamer override"
      value_template: >-
          {{  
            states('sensor.slaapkamer')|float > 100 or 
            (
              is_state('input_boolean.scene_special_in_bed', 'on')
            )
          }}