######## Aanwezigheidssensoren voor kamers
# Badkamer
- platform: template
  sensors:
    aanwezigheid_badkamer:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_badkamer') }) }}
      value_template: >-
          {{ 
              is_state('group.beweging_badkamer', 'on')
          }}
# Overloop eerste
- platform: template
  sensors:
    aanwezigheid_overloopeerste:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_overloopeerste') }) }}
      value_template: >-
          {{
              is_state('binary_sensor.group_aanwezigheid_overloopeerste', 'on')
          }}
# Kantoor
- platform: template
  sensors:
    aanwezigheid_kantoor:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_kantoor') }) }}
      value_template: >-
          {{
              is_state('binary_sensor.beweging_kantoor', 'on')
          }}
# Overloop tweede
- platform: template
  sensors:
    aanwezigheid_overlooptweede:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_overlooptweede') }) }}
      value_template: >-
          {{
              is_state('binary_sensor.group_aanwezigheid_overlooptweede', 'on')
          }}
#Slaapkamer
- platform: template
  sensors:
    aanwezigheid_slaapkamer:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_slaapkamer') }) }}
      value_template: >-
          {{
              is_state('binary_sensor.group_aanwezigheid_slaapkamer', 'on') or
              not is_state('sensor.slaapkamer_bedbezetting', 'leeg')
          }}
# Woonkamer
- platform: template
  sensors:
    aanwezigheid_woonkamer:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_woonkamer') }) }}
      value_template: >-
          {{
              is_state('binary_sensor.group_aanwezigheid_woonkamer', 'on')
          }}

# Hal
- platform: template
  sensors:
    aanwezigheid_hal:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_hal') }) }}
      value_template: >-
          {{
              is_state('binary_sensor.group_aanwezigheid_hal', 'on')
          }}