######## ESP-sensoren
#### Custom sensoren om rauwe ESP-sensoren te tweaken
#### geef ze allemaal toevoeging _ha

# Woonkamer
- platform: template
  sensors:
    woonkamer_lichtstatus:
      friendly_name: "Lichtstatus"
      device_class: light
      delay_on:
        seconds: 15 
      delay_off:
        minutes: 3
      value_template: >-
        {{ states('sensor.esp_woonkamer_lichtsensor')|float > states('input_number.esp_woonkamer_lichtsensor_treshold')|float }}