######## ESP-sensoren
#### Custom sensoren om rauwe ESP-sensoren te tweaken

# Woonkamer
- platform: template
  sensors:
    woonkamer_lichtstatus:
      friendly_name: "Lichtstatus"
      device_class: light
      delay_on:
        seconds: 15 
      delay_off:
        minutes: 3
      value_template: >-
        {{ states('sensor.woonkamer_lichtsensor')|float > states('input_number.esp_woonkamer_lichtsensor_treshold')|float }}
- platform: template
  sensors:
    woonkamer_pir_ha:
      friendly_name: "Woonkamer PIR"
      device_class: motion
      delay_on:
        seconds: 0 
      delay_off:
        minutes: 10
      value_template: >-
        {{ states('sensor.woonkamer_pir) }}