########### Lichtstatus
#Slaapkamer
- platform: template
  sensors:
    slaapkamer_lichtstatus:
      friendly_name: "Lichtstatus"
      device_class: light
      delay_on:
        minutes: 5
      delay_off:
        minutes: 5
      value_template: >-
        {{ states('sensor.beweging_slaapkamer_licht')|float(0) > states('input_number.lichtsensor_drempelwaarde_slaapkamer')|float }}
#Hal
- platform: template
  sensors:
    hal_lichtstatus:
      friendly_name: "Lichtstatus"
      device_class: light
      delay_on:
        minutes: 5 
      delay_off:
        minutes: 5
      value_template: >-
        {{ states('sensor.licht_woonkamer')|float(0) > states('input_number.lichtsensor_drempelwaarde_hal')|float(0) }}
#Overloop eerste
- platform: template
  sensors:
    overloopeerste_lichtstatus:
      friendly_name: "Lichtstatus"
      device_class: light
      delay_on:
        minutes: 5 
      delay_off:
        minutes: 5
      value_template: >-
        {{ states('sensor.licht_overloopeerste')|float(0) > states('input_number.lichtsensor_drempelwaarde_overloopeerste')|float(0) }}
#Overloop tweede
- platform: template
  sensors:
    overlooptweede_lichtstatus:
      friendly_name: "Lichtstatus"
      device_class: light
      delay_on:
        minutes: 5 
      delay_off:
        minutes: 5
      value_template: >-
        {{ states('sensor.licht_overlooptweede')|float(0) > states('input_number.lichtsensor_drempelwaarde_overlooptweede')|float(0) }}

#Woonkamer
- platform: template
  sensors:
    woonkamer_lichtstatus:
      friendly_name: "Lichtstatus"
      device_class: light
      delay_on:
        minutes: 5 
      delay_off:
        minutes: 5
      value_template: >-
        {{ states('sensor.licht_woonkamer')|float(0) > states('input_number.lichtsensor_drempelwaarde_woonkamer')|float(0) }}
