# Deze sensoren worden gebruikt om geen gebruik te maken van de bewegingsdetectie in de ruimte
### Bijvoorbeeld zodat 's nachts de lampen in de hal niet aangaan
- platform: template
  sensors:
    woonkamer_aanwezigheid_detectie:
      friendly_name: "Aanwezigheidsdetectie"
      value_template: >-
          {% if is_state('binary_sensor.woonkamer_lichtstatus','on')
          or is_state('group.geen_detectie_woonkamer', 'on')
          %}
          Off
          {% else %}
          On
          {% endif %}
- platform: template
  sensors:
    hal_aanwezigheid_detectie:
      friendly_name: "Aanwezigheidsdetectie"
      value_template: >-
        {% if is_state('input_boolean.scene_special_in_bed', 'on') 
        or is_state('group.geen_detectie_hal', 'on')
        %}
        On
        {% else %}
        On
        {% endif %}
- platform: template
  sensors:
    overloopeerste_aanwezigheid_detectie:
      friendly_name: "Aanwezigheidsdetectie"
      value_template: >-
          {% if is_state('binary_sensor.overloopeerste_lichtstatus','on') %}
          Off
          {% else %}
          On
          {% endif %}
- platform: template
  sensors:
    overlooptweede_aanwezigheid_detectie:
      friendly_name: "Aanwezigheidsdetectie"
      value_template: >-
          {% if is_state('binary_sensor.overlooptweede_lichtstatus','on') %}
          Off
          {% else %}
          On
          {% endif %}
- platform: template
  sensors:
    badkamer_aanwezigheid_detectie:
      friendly_name: "Aanwezigheidsdetectie"
      value_template: >-
        {% if is_state('input_boolean.scene_special_wolf_in_bed', 'on') 
        or is_state('group.geen_detectie_badkamer', 'on')
        %}
        Off
        {% else %}
        On
        {% endif %}
- platform: template
  sensors:
    slaapkamer_aanwezigheid_detectie:
      friendly_name: "Aanwezigheidsdetectie"
      value_template: >-
        {% if is_state('binary_sensor.slaapkamer_lichtstatus', 'on')
        or is_state('group.geen_detectie_slaapkamer', 'on')
        %}
          Off
        {%- else -%}
          On
        {%- endif %}