######## Aanwezigheidssensoren voor kamers
#### ESP regelt sensoren, hier kunnen evt zones worden gecombineerd, of xiaomi sensoren worden toegevoegd

######## Aanwezigheidssensor
#### Hoofdsensor, waarop de het licht schakelt
- platform: template
  sensors:
    aanwezigheid_woonkamer:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: 00:10
      value_template: >-
          {{
              is_state('binary_sensor.esp_woonkamer_pir', 'on')
          }}





# Lichtstatus
- platform: template
  sensors:
    woonkamer_lichtstatus:
      friendly_name: "Lichtstatus"
      device_class: light
      delay_on:
        seconds: 15 
      delay_off:
        minutes: 3
      value_template: >-
        {{ states('sensor.esp_woonkamer_lichtsensor')|float > states('input_number.esp_woonkamer_lichtsensor_treshold')|float }}