# Bed status (leeg of niet-leeg)        
- platform: template
  sensors:
    slaapkamer_bed:
      friendly_name: "Bed"
      device_class: occupancy
      delay_on:
        minutes: 3
      delay_off:
        minutes: 3
      value_template: >-
        {{ 
          not is_state('sensor.slaapkamer_bedbezetting', 'leeg') and
          not is_state('sensor.slaapkamer_bedbezetting', 'unavailable')
        }} 