######## Aanwezigheidssensoren voor kamers
#### ESP regelt sensoren, hier kunnen evt zones worden gecombineerd, of xiaomi sensoren worden toegevoegd

######## Aanwezigheidssensor
#### Hoofdsensor, waarop de het licht schakelt
- platform: template
  sensors:
    aanwezigheid_slaapkamer:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_slaapkamer') }) }}
      value_template: >-
          {{
              is_state('group.beweging_slaapkamer', 'on') or
              not is_state('sensor.slaapkamer_bedbezetting', 'leeg')
          }}

# Lichtstatus
- platform: template
  sensors:
    slaapkamer_lichtstatus:
      friendly_name: "Lichtstatus"
      device_class: light
      delay_on:
        minutes: 5
      delay_off:
        minutes: 5
      value_template: >-
        {{ states('sensor.beweging_slaapkamer_licht')|float > states('input_number.esp_slaapkamer_lichtsensor_threshold')|float }}

# Bed status (leeg of niet-leeg)        
- platform: template
  sensors:
    slaapkamer_bed:
      friendly_name: "Bed"
      device_class: occupancy
      delay_on:
        minutes: 3
      delay_off:
        minutes: 3
      value_template: >-
        {{ 
          not is_state('sensor.slaapkamer_bedbezetting', 'leeg') and
          not is_state('sensor.slaapkamer_bedbezetting', 'unavailable')
        }} 