- platform: template
  sensors:
    luchtkwaliteit_co2:
      friendly_name: "CO2 te hoog"
      delay_on: >-
        {{ ({ "minutes": states('input_number.luchtkwaliteit_co2_delay_on')|int(10) }) }}
      delay_off: >-
        {{ ({ "minutes": states('input_number.luchtkwaliteit_co2_delay_off')|int(10) }) }}
      value_template: >-
        {{ [ states('sensor.co2')|int(0) ]|max > states('input_number.luchtkwaliteit_co2_threshold')|int(1000)}}

- platform: template
  sensors:
    luchtkwaliteit_luchtvochtigheid:
      friendly_name: "Luchtvochtigheid te hoog"
      delay_on: >-
        {{ ({ "minutes": states('input_number.luchtkwaliteit_luchtvochtigheid_delay_on')|int(0) }) }}
      delay_off: >-
        {{ ({ "minutes": states('input_number.luchtkwaliteit_luchtvochtigheid_delay_off')|int(5) }) }}
      value_template: >-
        {{ 
          ( states('sensor.luchtvochtigheid_badkamer')|float - states('sensor.luchtvochtigheid_badkamer_statistics')|float ) / states('sensor.luchtvochtigheid_badkamer_statistics')|float > states('input_number.luchtkwaliteit_luchtvochtigheid_threshold')|float(0.1)
          and states('sensor.luchtvochtigheid_badkamer')|float > 65
        }}
        
- platform: template
  sensors:
    wtw_bypass:
      friendly_name: "WTW bypass"
      delay_on: 10
      delay_off: 10
      value_template: >-
        {{ states('sensor.knmi_thuis_gevoelstemperatuur')|float > 10 and 
            (
              [ states('sensor.temperatuur_badkamer' ), states('sensor.temperatuur_woonkamer'), states('sensor.temperatuur_slaapkamer' ) ]|float(22) > states('sensor.knmi_thuis_gevoelstemperatuur')|float(5) or
              [ states('sensor.temperatuur_badkamer' ), states('sensor.temperatuur_woonkamer'), states('sensor.temperatuur_slaapkamer' ) ]|float(22) > 23
            )
        }}
