- platform: template
  sensors:
    zomermaand:
      friendly_name: Zomermaand
      value_template: "{{ 3 < now().month < 11 }}"

# Is het nodig zonwering in te schakelen?
- platform: template
  sensors:
    zonweringweer:
      friendly_name: "Zonweringweer"
      delay_on: >-
        {{ ({ "minutes": states('input_number.zonwering_nodig_delay_on') }) }}
      delay_off: >-
        {{ ({ "minutes": states('input_number.zonwering_nodig_delay_off') }) }}
      value_template: >-
        {{ 
            is_state('binary_sensor.zomermaand', 'on')
            and
            states('sensor.delft_today_max') >= states('input_number.zonwering_buitentemperatuur_threshold')
            and
            int(states('sensor.irradiance')) >= int(states('input_number.zonwering_irradiance_threshold'))
            and
            states('sensor.temperatuur_woonkamer') >= states('input_number.zonwering_binnentemperatuur_threshold')          
        }}

- platform: template
  sensors:
    zon_achterkant:
      friendly_name: "Zon achterkant huis"
      value_template: >-
        {{
          state_attr("sun.sun", "elevation") > 15
          and
          state_attr("sun.sun", "azimuth") > 63
          and
          state_attr("sun.sun", "azimuth") < 197
        }}

- platform: template
  sensors:
    zon_voorkant:
      friendly_name: "Zon voorkant huis"
      value_template: >-
        {{
          state_attr("sun.sun", "elevation") > 10
          and
          state_attr("sun.sun", "azimuth") > 227
          and
          state_attr("sun.sun", "azimuth") < 293
        }}