- platform: template
  sensors:
    zomermaanden:
      friendly_name: Zomermaanden
      value_template: "{{ 3 < now().month < 11 }}"


# Is het nodig zonwering in te schakelen?
- platform: template
  sensors:
    zonwering_nodig:
      friendly_name: "Zonwering nodig"
      delay_on: >-
        {{ ({ "minutes": states('input_number.zonwering_nodig_delay_on') }) }}
      delay_off: >-
        {{ ({ "minutes": states('input_number.zonwering_nodig_delay_off') }) }}
      value_template: >-
        {{ 
            states('binary_sensor.zomermaanden' == "on")
            and
            states('sensor.delft_today_max') >= states('input_number.zonwering_buitentemperatuur_threshold')
            and
            states('sensor.irradiance') >= states('input_number.zonwering_irradiance_threshold')
            and
            states('sensor.temperatuur_woonkamer') >= states('input_number.zonwering_binnentemperatuur_threshold')          
        }}