- platform: workday
  country: NL
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun]

- platform: template
  sensors:
    kantoordag:
      friendly_name: "Kantoordag"
      value_template: >-
          {{ 
              is_state('group.aanwezigheid_personen', 'not_home')
              and is_state('binary_sensor.workday_sensor', 'on')
              and ( 20 < now().hour > 8 )
          }}

