- platform: werkdag
  country: NL
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun]

- platform: template
  sensors:
    kantoordag:
      friendly_name: "Kantoordag"
      device_class: occupancy
      delay_off: 
        hours: 1
      value_template: >-
          {{ 
              is_state('group.aanwezigheid_personen', 'off')
          }}
