######## Aanwezigheidssensoren voor kamers
#### ESP regelt sensoren, hier kunnen evt zones worden gecombineerd, of xiaomi sensoren worden toegevoegd

######## Aanwezigheidssensor
#### Hoofdsensor, waarop de het licht schakelt
- platform: template
  sensors:
    aanwezigheid_woonkamer:
      friendly_name: "Aanwezigheid"
      device_class: occupancy
      delay_off: >-
        {{ ({ "minutes": states('input_number.kamers_aanwezigheid_woonkamer') }) }}
      value_template: >-
          {{
              is_state('binary_sensor.group_aanwezigheid_woonkamer', 'on')
          }}

# Lichtstatus
- platform: template
  sensors:
    woonkamer_lichtstatus:
      friendly_name: "Lichtstatus"
      device_class: light
      delay_on:
        minutes: 5 
      delay_off:
        minutes: 5
      value_template: >-
        {{ states('sensor.licht_woonkamer')|float > states('input_number.lichtsensor_drempelwaarde_woonkamer')|float }}