###   ESP Woonkamer (zonde zithoek)
##### PIR
esp_woonkamer_pir_vertragingaan:
  name: Vertraging aan
  min: 0
  max: 15
  step: 0.5
esp_woonkamer_pir_vertraginguit:
  name: Vertraging uit
  min: 0
  max: 15
  step: 0.5
##### Lichtsensor
esp_woonkamer_lichtsensor_treshold:
  name: Drempelwaarde
  min: 0
  max: 1000
  step: 25
esp_woonkamer_lichtsensor_vertragingaan:
  name: Vertraging aan
  min: 0
  max: 15
  step: 0.5
esp_woonkamer_lichtsensor_vertraginguit:
  name: Vertraging uit
  min: 0
  max: 15
  step: 0.5