###   ESP Woonkamer (zonde zithoek)
##### Lichtsensor
esp_woonkamer_lichtsensor_threshold:
  name: Drempelwaarde
  min: 0
  max: 200
  step: 25
esp_slaapkamer_lichtsensor_threshold:
  name: Drempelwaarde
  min: 0
  max: 200
  step: 25